 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/trainers", type: :request do
  # Trainer. As you add validations to Trainer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Trainer.create! valid_attributes
      get trainers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      trainer = Trainer.create! valid_attributes
      get trainer_url(trainer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_trainer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      trainer = Trainer.create! valid_attributes
      get edit_trainer_url(trainer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Trainer" do
        expect {
          post trainers_url, params: { trainer: valid_attributes }
        }.to change(Trainer, :count).by(1)
      end

      it "redirects to the created trainer" do
        post trainers_url, params: { trainer: valid_attributes }
        expect(response).to redirect_to(trainer_url(Trainer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Trainer" do
        expect {
          post trainers_url, params: { trainer: invalid_attributes }
        }.to change(Trainer, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post trainers_url, params: { trainer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested trainer" do
        trainer = Trainer.create! valid_attributes
        patch trainer_url(trainer), params: { trainer: new_attributes }
        trainer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the trainer" do
        trainer = Trainer.create! valid_attributes
        patch trainer_url(trainer), params: { trainer: new_attributes }
        trainer.reload
        expect(response).to redirect_to(trainer_url(trainer))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        trainer = Trainer.create! valid_attributes
        patch trainer_url(trainer), params: { trainer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested trainer" do
      trainer = Trainer.create! valid_attributes
      expect {
        delete trainer_url(trainer)
      }.to change(Trainer, :count).by(-1)
    end

    it "redirects to the trainers list" do
      trainer = Trainer.create! valid_attributes
      delete trainer_url(trainer)
      expect(response).to redirect_to(trainers_url)
    end
  end
end
